influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    - /srv/docker/influxdb/data:/var/lib/influxdb

telegraf:
  image: telegraf:latest
  container_name: telegraf
  links:
    - influxdb
  volumes:
    - ./vsphere-stats.conf:/etc/telegraf/telegraf.conf:ro


grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  user: "0"
  links:
    - influxdb
  volumes:
    - /srv/docker/grafana/data:/var/lib/grafana
    - ./datasources.yml:/etc/grafana/provisioning/datasources/influxdb.yaml
    - ./dashboards.yml:/etc/grafana/provisioning/dashboards/influxdb.yaml
    - ./dashboards:/dashboards
