{
 "title": "VMware vSphere  - Hosts",
 "description": "VMware vSphere Dashboard using the new Telegraf plugin",
 "tags": [
  "VMware",
  "vSphere Hosts",
  "vSphere Telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "vcenter",
    "label": "vCenter Server",
    "query": "SHOW TAG VALUES FROM vsphere_host_cpu WITH KEY=vcenter"
   },
   {
    "name": "clustername",
    "label": "Cluster",
    "query": "SHOW TAG VALUES FROM vsphere_host_cpu WITH KEY=clustername WHERE \"vcenter\" =~ /$vcenter/"
   },
   {
    "name": "esxi",
    "label": "ESXi Server",
    "query": "SHOW TAG VALUES FROM vsphere_host_cpu WITH KEY=esxhostname WHERE \"vcenter\" =~ /$vcenter/"
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": "SHOW TAG VALUES FROM vsphere_datastore_disk WITH KEY=source WHERE \"vcenter\" =~ /$vcenter/"
   }
  ]
 },
 "panels": [
  { "title": "$esxi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "esxi" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_sys",
     "select": [
      [
       { "params": [ "uptime_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "select": [
      [
       { "params": [ "usagemhz_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "query": "SELECT last(\"totalCapacity_average\") * (last(\"usage_average\")) / 100 * 1024 FROM \"vsphere_host_mem\" WHERE (\"esxhostname\" =~ /^$esxi$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "active_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization Avg %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "% CPU Utilization Avg." }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "select": [
      [
       { "params": [ "utilization_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "RAM Usage in %" }
   ],
   "targets": [
    {
     "alias": "Usage percentage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Ready Avg %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "% CPU Ready Avg." }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "select": [
      [
       { "params": [ "readiness_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage in %",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "query": "SELECT last(\"totalCapacity_average\") * (last(\"usage_average\")) / 100 * 1024 FROM \"vsphere_host_mem\" WHERE (\"esxhostname\" =~ /^$esxi$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "KBs", "label": "Network Usage" }
   ],
   "targets": [
    {
     "alias": "$tag_interface bytesRx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_net",
     "select": [
      [
       { "params": [ "bytesRx_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    },
    {
     "alias": "$tag_interface bytesTx",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_net",
     "select": [
      [
       { "params": [ "bytesTx_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Disk Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "KBps" }
   ],
   "targets": [
    {
     "alias": "Write - $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_disk",
     "select": [
      [
       { "params": [ "totalReadLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    },
    {
     "alias": "Read - $tag_disk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_disk",
     "select": [
      [
       { "params": [ "totalWriteLatency_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Adapter Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_adapter Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "adapter" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_storageAdapter",
     "select": [
      [
       { "params": [ "numberReadAveraged_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    },
    {
     "alias": "$tag_adapter Write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_storageAdapter",
     "select": [
      [
       { "params": [ "numberWriteAveraged_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
     ]
    }
   ]
  }
 ]
}